[features]
seeds = false
skip-lint = false

[programs.localnet]
betting_pools = "BETSNNcnFGDW7yKKdPAJzxv8DmF3A6ovM7TYzFkDGyK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 